networks:
  internal:

services:
  webserver:
    build:
      dockerfile: Dockerfile
      tags:
        - albums
      args:
        PORT: "${PORT}"
    networks:
      - internal
    ports:
      - ${PORT}:${PORT}
