on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
        - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6.0.2

    - name: build docker
      shell: bash
      run: |
        set -x
        pwd
        ls -lah
        docker build . -t albums
